# Assignment: np.ones()

In [1]:
import numpy as np

In [9]:
# 1D
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
# 2D
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# 3D
np.ones((3,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

# Assignment: Create a 3D array with random

In [31]:
# 1D
np.random.random(5)

array([0.492761  , 0.6609289 , 0.01763271, 0.91348505, 0.08937969])

In [11]:
# 2D
np.random.random((4,3))

array([[0.22712483, 0.92660019, 0.53231907],
       [0.43600479, 0.77197952, 0.47177058],
       [0.66469656, 0.41744453, 0.05534231],
       [0.98458719, 0.42916408, 0.71582972]])

In [12]:
# 3D
np.random.random((3,2,2))

array([[[0.85482005, 0.82088016],
        [0.05988861, 0.84069251]],

       [[0.60518982, 0.38603792],
        [0.58457599, 0.61586292]],

       [[0.56905285, 0.08218395],
        [0.84543319, 0.94483923]]])

# assignment: np.eye()
We can change the diagonal in np.eye() as compared to np.identity()

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
b = np.eye(4,k=1)
print(b)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [25]:
b = np.eye(4,k=-1)
print(b)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
